steps:
  # Step 1: Build and package the Java app
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t',
        'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/java-app:$SHORT_SHA',
        '.'
      ]

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/java-app:$SHORT_SHA'
      ]

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'java-app',
        '--image', 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/java-app:$SHORT_SHA',
        '--platform', 'managed',
        '--region', 'REGION',
        '--allow-unauthenticated'
      ]

images:
  - 'REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/java-app:$SHORT_SHA'
